[package]
name = "aworkit-desktop"
version = "0.1.0"
description = "Aworkit desktop presentation shell"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aworkit-local-store = { path = "../../crates/aworkit-local-store" }
aworkit-protocol = { path = "../../crates/aworkit-protocol" }
aworkit-trusted-core = { path = "../../crates/aworkit-trusted-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-notification = "2.3.3"
tauri-plugin-opener = "2"

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
